import NavigationBar from "@/components/layout/NavigationBar";
import ReduxProvider from "@/components/ReduxProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Eczar, Work_Sans } from "next/font/google";
import "./globals.css";
import AuthInitializer from "@/components/AuthInitializer";
import Footer from "@/components/layout/Footer";

const eczar = Eczar({
  weights: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const workSans = Work_Sans({
  weights: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-eczar ${eczar.className} ${workSans.className} antialiased overflow-x-hidden`}
      >
        <ReduxProvider>
          <AuthInitializer />
          <NavigationBar />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
